---
# AgentSpec: Buffer UI Module
# Version: 1.1
# Last Updated: 2025-12-25

feature:
  name: "Buffer UI (Stage 3 Streaming)"
  description: "Manages the streaming buffer UI displayed during torrent playback, including backdrop fetching, splash screen, trailer links, and progress monitoring."
  version: "1.2"

files:
  - modules/streaming/buffer_ui.sh
  - modules/streaming/player.sh
  - modules/streaming/splash_progress.sh
  - scripts/python/fetch_backdrop.py
  - scripts/python/fetch_trailers.py

pipeline:
  - stage: backdrop_fetch
    description: "Fetch widescreen backdrop image from Google Images"
    inputs:
      - title: "Movie/show title"
      - content_type: "movie or show"
    outputs:
      - backdrop_image: "Path to downloaded backdrop file"
    timeout: "10 seconds (2 retries)"
    fallback_chain:
      - "Google Images backdrop (widescreen)"
      - "Poster file from catalog"
      - "Bundled default image (lib/torrent/img/movie_night.jpg)"
      - "Skip splash (empty string)"

  - stage: poster_caching
    description: "Download and cache poster image for preview"
    trigger: "STAGE2_POSTER is a URL"
    outputs:
      - local_poster: "Cached poster in ~/.cache/termflix/posters/"
    logic: "MD5 hash of URL used as filename"

  - stage: trailer_fetch
    description: "Fetch YouTube trailer links for the movie"
    script: "scripts/python/fetch_trailers.py"
    inputs:
      - title: "Movie/show title"
      - limit: "Number of trailers (default: 2)"
    outputs:
      - trailers: "List of title|url pairs"
    timeout: "5 seconds"

  - stage: splash_screen
    description: "Launch MPV splash screen with backdrop"
    condition: "launch_splash_screen available AND backdrop_image is valid file"
    outputs:
      - splash_pid: "Process ID of splash screen"
      - splash_socket: "IPC socket path"

  - stage: stream_torrent
    description: "Background process streaming the torrent"
    outputs:
      - stream_pid: "Process ID of streaming process"
      - status_file: "Path to buffer status file"

  - stage: fzf_buffer_ui
    description: "FZF interface showing buffering progress"
    features:
      - "Live preview with buffering percentage at TOP (always visible)"
      - "Poster display (viu/chafa/kitty)"
      - "Trailer links section with YouTube URLs"
      - "FZF listen port for API-driven refresh"
      - "Auto-refresh every 0.3s via background sidecar"
      - "Sidecar auto-abort: closes FZF when MPV exits"

data_flow:
  status_file_format: "progress|speed_bytes|peers|total_peers|buffered_mb|state|stream_url|peerflix_pid"
  states:
    - STARTING
    - ANALYZING
    - BUFFERING
    - READY
    - PLAYING
  env_vars:
    STAGE2_POSTER: "Path to cached poster image"
    STAGE2_TITLE: "Movie/show title"
    STAGE2_PLOT: "Synopsis text"
    STAGE2_SOURCES: "Source badges [TPB][YTS]"
    TERMFLIX_TRAILER_SCRIPT: "Path to fetch_trailers.py"
    TERMFLIX_POSTER_CACHE: "Poster cache directory"

resilience:
  - issue: "Backdrop fetch timeout on cold cache"
    solution: "Increased timeout from 3s to 10s"
  - issue: "Single quotes in movie titles break eval"
    solution: "tml_shell_escape function escapes special chars"
  - issue: "Unbound variable in cleanup trap"
    solution: "Safe expansion ${var:-} and trap restoration"
  - issue: "Poster is N/A or URL"
    solution: "Fallback chain + URL download with MD5 caching"
  - issue: "macOS throttles background window updates"
    solution: "Changed MPV splash to windowed mode (1280x720)"
  - issue: "FZF progress bar not visible (buried below poster)"
    solution: "Reorganized preview output: progress bar at TOP"
  - issue: "FZF doesn't close when MPV exits"
    solution: "Sidecar sends 'abort' to FZF when stream_pid dies"

integration:
  sources_from:
    - modules/ui/catalog/fzf_catalog.sh (Stage 2 selection)
  exports_to:
    - modules/torrent.sh (stream_torrent function)
  uses:
    - modules/ui/tml/parser/tml_parser.sh (layout parsing)
    - modules/ui/layouts/buffer-ui.xml (FZF layout)
    - scripts/python/fetch_trailers.py (trailer links)
