---
# AgentSpec: Buffer UI Module
# Last Updated: 2025-12-30

feature:
  name: "Buffer UI (Stage 3 Streaming)"
  version: "1.2.0"
  purpose: "Run the Stage 3 buffering UI: fetch artwork/trailers, start torrent streaming, and show live progress in an fzf UI."

pipeline:
  stages:
    - backdrop_fetch: "Best-effort fetch widescreen backdrop image (fallback chain)."
    - poster_caching: "Download/cache poster for preview when a URL is provided."
    - trailer_fetch: "Fetch YouTube trailer links (best-effort)."
    - splash_screen: "Optionally launch an MPV splash window with the backdrop."
    - stream_torrent: "Start the torrent streaming process and write a status file."
    - fzf_buffer_ui: "Run the fzf buffer UI (preview shows progress at the top)."

environment:
  variables:
    - "STAGE2_POSTER (URL or cached path)"
    - "STAGE2_TITLE"
    - "STAGE2_PLOT"
    - "STAGE2_SOURCES (e.g. [TPB][YTS])"
    - "TERMFLIX_TRAILER_SCRIPT (scripts/python/fetch_trailers.py)"
    - "TERMFLIX_POSTER_CACHE (~/.cache/termflix/posters)"
    - "THEME_STR_ICON_PLAY (optional theme symbol; may be seasonally overridden)"
    - "THEME_STR_ICON_READY (optional theme symbol; may be seasonally overridden)"
    - "TERMFLIX_LOGO_ICON (seasonal brand icon; not theme-driven)"
  dependencies:
    - "fzf"
    - "mpv"
    - "python3"
    - "curl"
    - "viu|chafa|kitty (optional for images)"

data_sources:
  - source: "Google Images"
    priority: 1
    endpoint: "Backdrop search"
    field: "Backdrop image URL"
    format: "HTTP image"
    notes: "Best-effort; may fail due to throttling/format changes."
  - source: "YouTube (via scripts)"
    priority: 2
    endpoint: "Trailer search"
    field: "title|url"
    format: "Text"
    notes: "Best-effort; scripts/python/fetch_trailers.py"

local_resources:
  - path: "~/.cache/termflix/posters/"
    format: "Image files"
    purpose: "Poster cache (MD5 filenames)"
    persistence: "Cache"
  - path: "lib/torrent/img/movie_night.jpg"
    format: "JPG"
    purpose: "Bundled fallback backdrop"
    persistence: "Permanent"
  - path: "modules/ui/layouts/buffer-ui.xml"
    format: "XML"
    purpose: "TML/fzf layout for Stage 3 UI"
    persistence: "Permanent"

outputs:
  format: "status file + stream URL"
  schema:
    status_file_format: "progress|speed_bytes|peers|total_peers|buffered_mb|state|stream_url|peerflix_pid"
    states: "STARTING|ANALYZING|BUFFERING|READY|PLAYING"

resilience:
  fallback_chain:
    - "Google backdrop"
    - "Catalog poster"
    - "Bundled default image"
    - "No splash"
  retries: "Backdrop: 2 retries within ~10s; trailers: best-effort within ~5s"
  default_behavior: "If artwork/trailers fail, continue streaming with a simplified UI."
  notes:
    - issue: "Backdrop fetch timeout on cold cache"
      solution: "Timeout increased to ~10s with retries."
    - issue: "Single quotes in titles break eval"
      solution: "TML parser uses tml_shell_escape and argv execution (no eval)."
    - issue: "Unbound variable in cleanup trap"
      solution: "Safe expansion ${var:-} + trap restoration."
    - issue: "Poster is N/A or URL"
      solution: "Fallback chain + URL download with MD5 caching."
    - issue: "macOS throttles background window updates"
      solution: "MPV splash uses windowed mode (1280x720)."
    - issue: "Progress bar not visible"
      solution: "Preview output keeps progress at TOP."
    - issue: "FZF doesn't close when MPV exits"
      solution: "Sidecar sends 'abort' to fzf when stream_pid dies."

integration:
  cross_references:
    - docs/specs/Catalog.spec.yaml (logic_flow.Stage2_to_Stage3)
  ui_component: "Stage 3 Buffer UI"
  file: "modules/streaming/buffer_ui.sh"
  trigger: "User accepts a version in Stage 2 (movie/episode version picker)"

implementation:
  modules:
    - path: "modules/streaming/buffer_ui.sh"
      role: "Stage 3 controller + fzf UI"
    - path: "modules/streaming/player.sh"
      role: "MPV player integration"
    - path: "modules/streaming/splash_progress.sh"
      role: "Splash window helpers"
    - path: "modules/torrent.sh"
      role: "Torrent streaming orchestration"
    - path: "scripts/python/fetch_backdrop.py"
      role: "Backdrop fetching"
    - path: "scripts/python/fetch_trailers.py"
      role: "Trailer fetching"
  entry_points:
    - "modules/ui/catalog/fzf_catalog.sh (Stage 2 accept path)"

logic_flow:
  Stage2_to_Stage3:
    goal: "Start buffering UI after a version is selected."
    function: "buffer_ui.sh (Stage 3 entry)"
    strategy:
      - "Stage 2 version picker resolves magnet/source/quality."
      - "Stage 2 exports Stage 2 metadata (title, poster, plot, sources) for Stage 3."
      - "Stage 3 launches the buffer UI via the TML layout and begins streaming/progress monitoring."
