# Machine-Readable Specification for Termflix Catalog
# defined_in: 
#   - modules/catalog.sh
#   - modules/ui/catalog/fzf_catalog.sh

feature:
  name: Catalog & Navigation
  version: 1.0.0
  purpose: "Display aggregated torrent results, handle pagination, and manage navigation interactions."

pipeline:
  stages:
    - fetch: "Retrieve data via `catalog.sh` (wraps fetching modules)"
    - cache: "Store results in `~/.config/termflix/cache`"
    - paginate: "Slice results for current view (default 50 items/page)"
    - display: "Render UI using FZF (via `fzf_catalog.sh`)"
    - interact: "Handle user keybindings (Nav, Search, Sort)"

environment:
  variables:
    - "CURRENT_CATEGORY (movies|shows|all)"
    - "CURRENT_PAGE (integer)"
    - "TERMFLIX_PREFETCH_PID (PID of background fetcher)"
    - "TERMFLIX_STAGE1_CONTEXT (catalog|search)"
    - "CURRENT_LANGUAGE (ISO 639-1 code; empty means no filter)"
    - "CURRENT_MIN_RATING (0 means no filter)"
    - "TERMFLIX_LOGO_ICON (seasonal brand icon; not theme-driven)"
    - "TERMFLIX_STATUS_MID_ICON (optional mid-label icon for bottom help label)"
  dependencies:
    - "fzf"
    - "xmllint"

data_sources:
  - source: "Torrent providers"
    priority: 1
    endpoint: "TPB/YTS adapters (see modules/torrent.sh + modules/catalog.sh)"
    field: "title/year/quality/size/seeds/magnet"
    format: "Pipe-delimited rows"
    notes: "Exact sources depend on routing (movies/shows) and provider availability."

local_resources:
  - path: "~/.config/termflix/cache"
    format: "Text/JSON (implementation-dependent)"
    purpose: "Cached catalog pages and derived data"
    persistence: "Cache"

logic_flow:
  Stage1_to_Stage2:
    goal: "Enter version selection when a title has multiple sources or user requests it."
    function: "handle_fzf_selection (COMBINED gate)"
    strategy:
      - "Parse Stage 1 selection into key, index, rest_data."
      - "If Ctrl+L on a single-source item, wrap it as COMBINED and proceed."
      - "If rest_data is COMBINED, build version options and launch Stage 2 picker."
      - "If not COMBINED, stream immediately (skip Stage 2)."
  Stage2_to_Stage3:
    goal: "Start streaming after the user selects a version."
    function: "perform_streaming"
    strategy:
      - "Abort (Ctrl+H/Esc) returns to Stage 1 without streaming."
      - "Accept (Enter/Ctrl+L for episode picker) yields a selected index."
      - "Resolve magnet/source/quality and launch Stage 3 buffer UI."

resilience:
  fallback_chain:
    - "Use cache when fetch fails"
    - "Show error message when no cache exists"
  default_behavior: "Never stream unless user explicitly accepts a selection."
  retries: "Provider-dependent (catalog adapters may retry internally)"
  notes:
    - issue: "Stage 1 to Stage 2 transition crash (--exit-0 flag)"
      solution: "Removed --exit-0 from FZF command to prevent silent exits on empty selection."
    - issue: "Single quotes in titles breaking eval"
      solution: "TML parser uses tml_shell_escape; caller passes args via argv arrays."
    - issue: "Locked episodes clobber date column"
      solution: "Reserve a fixed-width lock column even when unlocked; size table using pane width."

implementation:
  modules:
    - path: "modules/catalog.sh"
      role: "Catalog fetching + caching orchestration"
    - path: "modules/ui/catalog/fzf_catalog.sh"
      role: "Stage 1 catalog + Stage 2 version picker"
      functions:
        - name: "show_fzf_catalog"
          input: "catalog data (pages)"
          output: "selected row / key"
        - name: "handle_fzf_selection"
          input: "selected row"
          output: "stage transition (stream or stage2 picker)"
    - path: "modules/ui/catalog/preview_fzf.sh"
      role: "Stage 1 preview script (shows episode table)"
    - path: "modules/ui/pickers/episode_picker.sh"
      role: "Episode picker UI (shows)"
    - path: "bin/termflix"
      role: "Popup filter pickers (type/sort/genre/year/rating/language/search)"
  entry_points:
    - "bin/termflix (catalog flows)"

integration:
  ui_component: "Stage 1 Catalog + Stage 2 Version Picker"
  file: "modules/ui/catalog/fzf_catalog.sh"
  trigger: "User navigates catalog, selects an item, or invokes filters/search"
