# Machine-Readable Specification for Termflix Catalog
# defined_in: 
#   - modules/catalog.sh
#   - modules/ui/catalog/fzf_catalog.sh

feature:
  name: Catalog & Navigation
  version: 1.0.0
  purpose: "Display aggregated torrent results, handle pagination, and manage navigation interactions."

pipeline:
  stages:
    - fetch: "Retrieve data via `catalog.sh` (wraps fetching modules)"
    - cache: "Store results in `~/.config/termflix/cache`"
    - paginate: "Slice results for current view (default 50 items/page)"
    - display: "Render UI using FZF (via `fzf_catalog.sh`)"
    - interact: "Handle user keybindings (Nav, Search, Sort)"

ui_components:
  - component: "Main Catalog"
    file: "modules/ui/catalog/fzf_catalog.sh"
    function: "show_fzf_catalog"
    description: "Primary FZF interface showing list of titles."
    keybindings:
      "Ctrl+F": "Search Mode"
      "Ctrl+O": "Category: Movies"
      "Ctrl+S": "Category: Shows"
      "Ctrl+L": "Force version picker for single-source items"
      "Ctrl+Right or >": "Next Page"
      "Ctrl+Left or <": "Previous Page"
      "Enter": "Select Item"

  - component: "Show Preview (Episode Table)"
    file: "modules/ui/catalog/preview_fzf.sh"
    function: "N/A (fzf preview script)"
    description: "Stage 1 preview pane renderer for TV shows; includes a Season Episodes table."
    notes:
      - "Uses `FZF_PREVIEW_COLUMNS` for preview pane width when available (fzf-provided)."
      - "Episode table reserves a fixed-width lock column so locked episodes don't shift/clobber the date column."
      - "Titles are not truncated by Termflix; some titles may contain `...` upstream (TMDB season data)."

  - component: "Episode Picker"
    file: "modules/ui/pickers/episode_picker.sh"
    function: "episode_picker"
    description: "Episode list UI for shows before version selection."
    keybindings:
      "Enter": "Select episode"
      "Ctrl+L": "Select episode (same as Enter), then open version picker"
      "Ctrl+E or Ctrl+S": "Switch season"
      "Ctrl+H or Esc": "Back to catalog"

  - component: "Version Picker (Stage 2)"
    file: "modules/ui/catalog/fzf_catalog.sh"
    function: "handle_fzf_selection"
    description: "Secondary FZF interface for selecting specific qualities/sources for a title (movies and episode results)."
    trigger: "Selecting a COMBINED entry from Main Catalog or pressing Ctrl+L on a single-source entry to wrap it as COMBINED."
    behavior:
      - "Abort (Ctrl+H/Esc) returns to Stage 1."
      - "Accept (Enter/Ctrl+L in episode picker) selects a version and proceeds to Stage 3 streaming."

data_flow:
  fetching_strategy:
    description: "Hybrid synchronous/asynchronous fetching."
    sync: "Pages 1-5 loaded immediately for responsiveness."
    async: "Pages 6-15+ fetched in background (`TERMFLIX_PREFETCH_PID`)."
    caching: "Results deduped and cached by title."

  state_management:
    env_vars:
      CURRENT_CATEGORY: "movies | shows | all"
      CURRENT_PAGE: "Integer"
      TERMFLIX_PREFETCH_PID: "PID of background fetcher"
      TERMFLIX_STAGE1_CONTEXT: "catalog | search"

logic_flow:
  Stage1_to_Stage2:
    goal: "Enter version selection when a title has multiple sources or user requests it."
    function: "handle_fzf_selection (COMBINED gate)"
    strategy:
      - "Parse Stage 1 selection into key, index, rest_data."
      - "If Ctrl+L on a single-source item, wrap it as COMBINED and proceed."
      - "If rest_data is COMBINED, build version options and launch Stage 2 picker."
      - "If not COMBINED, stream immediately (skip Stage 2)."
  Stage2_to_Stage3:
    goal: "Start streaming after the user selects a version."
    function: "perform_streaming"
    strategy:
      - "Abort (Ctrl+H/Esc) returns to Stage 1 without streaming."
      - "Accept (Enter/Ctrl+L for episode picker) yields a selected index."
      - "Resolve magnet/source/quality and launch Stage 3 buffer UI."

error_handling:
  - situation: "Empty Selection"
    behavior: "Loop breaks only if explicitly cancelled. Empty strings without cancel code are ignored/logged."
  - situation: "Fetch Failure"
    behavior: "Fallback to cache if available, else show error message."

resilience:
  - issue: "Stage 1 to Stage 2 transition crash (--exit-0 flag)"
    solution: "Removed --exit-0 from FZF command to prevent silent exits on empty selection"
  - issue: "Single quotes in movie titles breaking eval"
    solution: "TML parser uses tml_shell_escape for double-quote safe embedding"
  - issue: "Locked episodes misalign/clobber date column"
    solution: "Reserve a fixed-width lock column (2 cols) even when unlocked, and size the table using the preview/list pane width."
