---
# AgentSpec: TML Parser Module
# Last Updated: 2025-12-30

feature:
  name: "TML Parser (Terminal Markup Language)"
  version: "2.0.0"
  purpose: "Parse XML/TML layouts into fzf arguments and render menu-bar headers with theme + seasonal integration."

pipeline:
  stages:
    - parse: "Parse a .xml/.tml layout and build `TML_FZF_ARGS` + `TML_EXPECT_KEYS`."
    - render_header: "Render the TML `menu-bar` into an ANSI header string."
    - run_fzf: "Execute `fzf` using argv arrays (no eval)."

environment:
  variables:
    - "FZF_PREVIEW_COLUMNS (fzf-provided: preview pane width in columns for --preview commands)"
    - "FZF_PREVIEW_LINES (fzf-provided: preview pane height in lines for --preview commands)"
    - "TML_VAR_* (exported variables used by tml_eval/tml_eval_bool)"
    - "FZF_DEFAULT_OPTS (callers may temporarily clear this to prevent layout leakage into popup pickers)"
    - "LC_ALL/LANG (callers may force UTF-8 for unicode-heavy menus)"
    - "RUNEWIDTH_EASTASIAN (fzf respects this; callers may set to 1 for more stable unicode width handling in tmux)"
    - "THEME_STR_* (theme string/symbol tokens exported by theme loader)"
    - "TERMFLIX_LOGO_ICON (seasonal brand icon prefix + 🍿; not theme-driven)"
    - "TERMFLIX_STATUS_MID_ICON (optional mid-label icon for the bottom shortcut-help label)"
  dependencies:
    - "xmllint"
    - "fzf"

local_resources:
  - path: "modules/ui/tml/schema/tml-1.0.xsd"
    format: "XSD"
    purpose: "TML/XML schema reference (documentation + validation aid)"
    persistence: "Permanent"
  - path: "modules/ui/layouts/*.xml"
    format: "XML"
    purpose: "fzf-layout definitions used by tml_parse"
    persistence: "Permanent"
  - path: "modules/ui/layouts/*.tml"
    format: "TML"
    purpose: "Declarative menu-bar/header templates"
    persistence: "Permanent"

implementation:
  modules:
    - path: "modules/ui/tml/parser/tml_parser.sh"
      role: "Parser + renderer"
      functions:
        - name: "tml_parse"
          input: "layout_file"
          output: "TML_FZF_ARGS, TML_EXPECT_KEYS"
        - name: "tml_render_header"
          input: "layout_file"
          output: "ANSI header string"
        - name: "tml_run_fzf"
          input: "stdin options + parsed TML_FZF_ARGS"
          output: "fzf selection + return code"
        - name: "tml_eval"
          input: "string with ${var} expansions"
          output: "expanded string"
        - name: "tml_eval_bool"
          input: "boolean expression"
          output: "true/false"
        - name: "tml_shell_escape"
          input: "untrusted string"
          output: "safe double-quoted string"
        - name: "tml_attr"
          input: "xpath + file"
          output: "attribute value"
        - name: "tml_text"
          input: "xpath + file"
          output: "text content"
        - name: "tml_exists"
          input: "xpath + file"
          output: "true/false"
        - name: "tml_count"
          input: "xpath + file"
          output: "count"
        - name: "tml_get_options"
          input: "layout_file"
          output: "newline-separated options"
  entry_points:
    - "modules/ui/catalog/fzf_catalog.sh"
    - "modules/ui/pickers/*.sh"
    - "modules/streaming/buffer_ui.sh"

outputs:
  format: "Bash exports + argv arrays"
  schema:
    TML_FZF_ARGS: "Space-delimited fzf args string; parsed into an argv array by `tml_run_fzf`."
    TML_EXPECT_KEYS: "Comma-separated list of keys for `fzf --expect`."

resilience:
  fallback_chain:
    - "Escape/expand header via tml_shell_escape + tml_eval"
    - "Execute fzf via argv arrays (no eval)"
  default_behavior: "On parse failures, return empty args; callers handle as an error path."

logic_flow:
  env_expansion:
    goal: "Allow layouts to reference env vars without eval injection."
    function: "tml_eval"
    strategy:
      - "Support `${var}`."
      - "Support `${var-default}` (default only when unset)."
      - "Support `${var:-default}` (default when unset OR empty)."
      - "Apply escaping for attribute contexts before passing to fzf."

integration:
  ui_component: "All fzf-based pickers/layouts"
  file: "modules/ui/tml/parser/tml_parser.sh"
  trigger: "Any UI flow that parses and runs a layout via tml_run_fzf"
