---
# AgentSpec: Watch History Module
# Version: 1.2
# Last Updated: 2025-12-26

feature:
  name: "Watch History"
  description: "Tracks user watch progress for movies and shows, displaying resume indicators in Stage 2 version picker."
  version: "1.2"

files:
  - modules/torrent.sh (record_watch_progress function)
  - ~/.config/termflix/watch_history.json

data_model:
  storage: "~/.config/termflix/watch_history.json"
  key_format: "Torrent hash (40-char hex, lowercase)"
  fields:
    title: "Movie/show title"
    last_position: "Seconds watched"
    duration: "Total duration in seconds"
    percentage: "Calculated watch percentage"
    quality: "Video quality (1080p, 720p, etc.)"
    size: "File size"
    last_watched: "ISO 8601 timestamp"
    completed: "Boolean (>90% watched)"

position_extraction:
  method_1:
    description: "MPV watch_later file"
    path: "~/.config/termflix/watch_later/{md5(url)}.conf"
    field: "start="
    status: "Not created for HTTP streams"
    
  method_2:
    description: "MPV terminal log parsing"
    log_file: "$TMPDIR/termflix_mpv_debug.log"
    pattern: "AV: HH:MM:SS / HH:MM:SS"
    mpv_flags:
      - "--terminal=yes"
      - "--msg-level=all=status"
    status: "Works for direct peerflix path only"
    
  method_3:
    description: "IPC socket position capture during playback"
    implementation: "Playback loop polls every 5 seconds via socat"
    env_vars:
      - "TERMFLIX_IPC_POSITION"
      - "TERMFLIX_IPC_DURATION"
    status: "Implemented - needs verification"

pipeline:
  - stage: set_globals
    vars: [TERMFLIX_WATCH_SOURCE, TERMFLIX_WATCH_STREAM_URL, TERMFLIX_MPV_LOG]
      
  - stage: playback
    description: "User watches video via MPV"
    
  - stage: ipc_capture
    description: "Poll MPV via IPC every 5 seconds during playback"
    condition: "TERMFLIX_SPLASH_SOCKET exists"
    
  - stage: record_progress
    trigger: "MPV exit"
    function: "record_watch_progress"

display:
  location: "Stage 2 version picker (right column)"
  format: "👀 icon + percentage"

known_issues:
  - issue: "Position shows 0% for splash screen path"
    root_cause: "MPV via IPC transition doesn't output to log file"
    status: "INVESTIGATING - IPC capture method added"

debug:
  log_file: "/tmp/termflix_history_debug.log"
