---
# AgentSpec: Watch History Module
# Version: 1.2
# Last Updated: 2025-12-26

feature:
  name: "Watch History"
  description: "Tracks user watch progress for movies and shows, displaying resume indicators in Stage 2 version picker."
  version: "1.2"

files:
  - modules/torrent.sh (record_watch_progress function)
  - ~/.config/termflix/watch_history.json

data_model:
  storage: "~/.config/termflix/watch_history.json"
  key_format: "Torrent hash (40-char hex, lowercase)"
  fields:
    title: "Movie/show title"
    last_position: "Seconds watched"
    duration: "Total duration in seconds"
    percentage: "Calculated watch percentage"
    quality: "Video quality (1080p, 720p, etc.)"
    size: "File size"
    last_watched: "ISO 8601 timestamp"
    completed: "Boolean (>=95% watched)"

position_extraction:
  method_1:
    description: "MPV watch_later file"
    path: "~/.config/termflix/watch_later/{md5(url)}.conf"
    field: "start="
    status: "Primary; MPV is launched with `--watch-later-directory` + `--save-position-on-quit` so HTTP streams persist progress"
    
  method_2:
    description: "MPV IPC polling during playback"
    implementation: "Playback loop polls every 5 seconds via socat"
    env_vars:
      - "TERMFLIX_IPC_POSITION"
      - "TERMFLIX_IPC_DURATION"
    status: "Primary fallback when watch_later file is missing"

  method_3:
    description: "MPV terminal log parsing (last resort)"
    log_file: "$TMPDIR/termflix_mpv_<port>_<random>.log"
    pattern: "AV: HH:MM:SS / HH:MM:SS"
    mpv_flags:
      - "--terminal=yes"
      - "--msg-level=all=status"
    notes:
      - "MPV status lines often use carriage returns; log parsing normalizes CR->NL."
    status: "Fallback only"

pipeline:
  - stage: set_globals
    vars: [TERMFLIX_WATCH_SOURCE, TERMFLIX_WATCH_STREAM_URL, TERMFLIX_MPV_LOG, TERMFLIX_MPV_IPC_SOCKET]
      
  - stage: playback
    description: "User watches video via MPV"
    
  - stage: ipc_capture
    description: "Poll MPV via IPC every 5 seconds during playback"
    condition: "TERMFLIX_SPLASH_SOCKET exists"
    
  - stage: record_progress
    trigger: "MPV exit"
    function: "record_watch_progress"

display:
  location: "Stage 2 version picker (right column)"
  format: "👀 icon + percentage"

known_issues:
  - issue: "Multiple titles show identical progress (stale MPV log parse)"
    root_cause: "Shared/append-only MPV log and status lines written with carriage returns"
    status: "FIXED - use per-playback log + prefer watch_later/IPC"

debug:
  log_file: "/tmp/termflix_history_debug.log"
